using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using NeuralNetwork;


///<summary>
/// Class that is responsible for run managment
///</summary>
public class RunManager : MonoBehaviour
{

    public Run currentRun;
    //List of all results generated by any agent manager
    private List<Run> _runs = new List<Run>();
    private int _runNum = 0;
    [SerializeField]
    private GameObject _agentPrefab;

    ModelManager modelManager = null;
    // Start is called before the first frame update
    void Start()
    {
        Run.agentPrefab = _agentPrefab;
        currentRun = StartNewRun();
    }

    // Update is called once per frame
    void Update()
    {

    }

    Run StartNewRun()
    {
	   // modelManager = new ModelManager(JsonService.LoadModelsList((TextAsset)Resources.Load("20-01-14_20-23-44")));

        Run r = null;

        if (modelManager == null)
        {
            r = new Run(25);
            modelManager = new ModelManager(r.agents.Select(x => x.GetComponent<Agent>().network).ToList(), 0.05f);
        }
        else
        {
            modelManager.SaveTop(5);//kill all models and save top 5
            modelManager.Expand(); //expand models list to original size
            r = new Run(modelManager.Models);
        }
        r.runName = "Run #" + _runNum;
        r.RunComplete += OnRunEnded;
        r.BeginRun();
        return r;
    }

    void OnRunEnded(object sender, List<Run.AgentResult> results)
    {
        //Accept only Run senders 
        if (!(sender is Run r))
            throw new ArgumentException("Sender is not of the type Run");


        //Unsubscribe from sender to avoid memory leak
        r.RunComplete -= OnRunEnded;

        //store run
        _runs.Add(r);
        List<NetworkModel> models = r.results.OrderBy(x => x.score).Select(x => x.model).ToList();
        Debug.Log(models[0].ToString());
        currentRun = StartNewRun();
    }
}
