using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using NeuralNetwork;


///<summary>
/// Class that is responsible for run managment
///</summary>
public class RunManager : MonoBehaviour
{
    //List of all results generated by any agent manager
    List<Run> runs = new List<Run>();
    int run_num = 0;
    [SerializeField]
    GameObject agentPrefab;

    ModelManager modelManager = null;
    // Start is called before the first frame update
    void Start()
    {
        Run.agentPrefab = agentPrefab;
        //For now the behaviour is to indefinetely repeat randomized runs;
        StartNewRun();
    }

    // Update is called once per frame
    void Update()
    {

    }

    void StartNewRun()
    {
        Run r = null;
        if (modelManager == null)
        {
            r = new Run(25);
            modelManager = new ModelManager(r.agents.Select(x => x.GetComponent<Agent>().network).ToList(), 0.05f);
        }
        else
        {
            modelManager.SaveTop(5);//kill all models and save top 5
            modelManager.Expand(); //expand models list to original size
            r = new Run(modelManager.Models);
        }
        r.runName = "Run #" + run_num;
        r.RunComplete += OnRunEnded;
        r.BeginRun();
    }

    void OnRunEnded(object sender, List<Run.AgentResult> results)
    {
        //Accept only Run senders 
        if (!(sender is Run r))
            throw new ArgumentException("Sender is not of the type Run");


        //Unsubscribe from sender to avoid memory leak
        r.RunComplete -= OnRunEnded;

        //store run
        runs.Add(r);
        List<NetworkModel> models = r.results.OrderBy(x => x.score).Select(x => x.model).ToList();

        StartNewRun();
    }
}
